image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
    - cp -r {audio,yoga,tech,entrepeneur} public/.
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
    - cp -r {audio,yoga,tech,entrepeneur} public/.
  artifacts:
    paths:
    - public
  only:
  - master
