# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Leon van Kammen
tagline:          micro devtrepeneur / tech integration ninja from Europe
url:              http://coderofsalvation.github.io
paginate:         4
baseurl:          /
author:
  name:           Leon van Kammen
  url:            https://twitter.com/coderofsalvatio
  email:          info@leon.vankammen.eu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/foo
