# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  hard_wrap: false

#exclude: 
#  - audio
#  - yoga
#  - entrepeneur
#  - tech

keep_files: [audio,yoga,entrepeneur,tech]
  
highlighter: rouge
#pygments:         true

# Permalinks
#permalink:        pretty

# Setup
encoding: UTF-8
title: Leon van Kammen
tagline: micro devtrepeneur / web integration ninja from Europe
url: http://coderofsalvation.github.io
paginate: 4
author:
  name: Leon van Kammen
  url: https://twitter.com/coderofsalvatio
  email: info@leon.vankammen.eu

gems: [jekyll-paginate]

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/coderofsalvation/coderofsalvation.github.io
